from tg21_sample_data.model import *
import transaction

def upgrade(conf):
    DBSession.add( State("Alaska", "AK") )
    DBSession.add( State("Alabama" , "AL") )
    DBSession.add( State("Arkansas" , "AR") )
    DBSession.add( State("Arizona" , "AZ") )
    DBSession.add( State("California" , "CA") )
    DBSession.add( State("Colorado" , "CO") )
    DBSession.add( State("Connecticut" , "CT") )
    DBSession.add( State("Delaware" , "DE") )
    DBSession.add( State("District of Columbia" , "DC") )
    DBSession.add( State("Florida" , "FL") )
    DBSession.add( State("Georgia" , "GA") )
    DBSession.add( State("Hawaii" , "HI") )
    DBSession.add( State("Iowa" , "IA") )
    DBSession.add( State("Idaho" , "ID") )
    DBSession.add( State("Illinois" , "IL") )
    DBSession.add( State("Indiana" , "IN") )
    DBSession.add( State("Kansas" , "KS") )
    DBSession.add( State("Kentucky" , "KY") )
    DBSession.add( State("Louisiana" , "LA") )
    DBSession.add( State("Massachusetts" , "MA") )
    DBSession.add( State("Maryland" , "MD") )
    DBSession.add( State("Maine" , "ME") )
    DBSession.add( State("Michigan" , "MI") )
    DBSession.add( State("Minnesota" , "MN") )
    DBSession.add( State("Mississippi" , "MS") )
    DBSession.add( State("Missouri" , "MO") )
    DBSession.add( State("Montana" , "MT") )
    DBSession.add( State("North Carolina" , "NC") )
    DBSession.add( State("North Dakota" , "ND") )
    DBSession.add( State("Nebraska" , "NE") )
    DBSession.add( State("New Hampshire" , "NH") )
    DBSession.add( State("New Jersey" , "NJ") )
    DBSession.add( State("New Mexico" , "NM") )
    DBSession.add( State("Nevada" , "NV") )
    DBSession.add( State("New York" , "NY") )
    DBSession.add( State("Ohio" , "OH") )
    DBSession.add( State("Oklahoma" , "OK") )
    DBSession.add( State("Oregon" , "OR") )
    DBSession.add( State("Pennsylvania" , "PA") )
    DBSession.add( State("Rhode Island" , "RI") )
    DBSession.add( State("South Carolina" , "SC") )
    DBSession.add( State("South Dakota" , "SD") )
    DBSession.add( State("Tennessee" , "TN") )
    DBSession.add( State("Texas" , "TX") )
    DBSession.add( State("Utah" , "UT") )
    DBSession.add( State("Virginia" , "VA") )
    DBSession.add( State("Vermont" , "VT") )
    DBSession.add( State("Washington" , "WA") )
    DBSession.add( State("Wisconsin" , "WI") )
    DBSession.add( State("West Virginia" , "WV") )
    DBSession.add( State("Wyoming" , "WY") )
    
    transaction.commit()
    
def downgrade(conf):
    DBSession.query(State).filter_by(postal_code = "AK").delete()
    DBSession.query(State).filter_by(postal_code = "AL").delete()
    DBSession.query(State).filter_by(postal_code = "AR").delete()
    DBSession.query(State).filter_by(postal_code = "AZ").delete()
    
    DBSession.query(State).filter_by(postal_code = "CA").delete()
    DBSession.query(State).filter_by(postal_code = "CO").delete()
    DBSession.query(State).filter_by(postal_code = "CT").delete()
    DBSession.query(State).filter_by(postal_code = "DE").delete()
    DBSession.query(State).filter_by(postal_code = "DC").delete()
    DBSession.query(State).filter_by(postal_code = "FL").delete()
    DBSession.query(State).filter_by(postal_code = "GA").delete()
    DBSession.query(State).filter_by(postal_code = "HI").delete()
    DBSession.query(State).filter_by(postal_code = "IA").delete()
    DBSession.query(State).filter_by(postal_code = "ID").delete()
    DBSession.query(State).filter_by(postal_code = "IL").delete()
    DBSession.query(State).filter_by(postal_code = "IN").delete()
    DBSession.query(State).filter_by(postal_code = "KS").delete()
    DBSession.query(State).filter_by(postal_code = "KY").delete()
    DBSession.query(State).filter_by(postal_code = "LA").delete()
    DBSession.query(State).filter_by(postal_code = "MA").delete()
    DBSession.query(State).filter_by(postal_code = "MD").delete()
    DBSession.query(State).filter_by(postal_code = "ME").delete()
    DBSession.query(State).filter_by(postal_code = "MI").delete()
    DBSession.query(State).filter_by(postal_code = "MN").delete()
    DBSession.query(State).filter_by(postal_code = "MS").delete()
    DBSession.query(State).filter_by(postal_code = "MO").delete()
    DBSession.query(State).filter_by(postal_code = "MT").delete()
    DBSession.query(State).filter_by(postal_code = "NC").delete()
    DBSession.query(State).filter_by(postal_code = "ND").delete()
    DBSession.query(State).filter_by(postal_code = "NE").delete()
    
    DBSession.query(State).filter_by(postal_code = "NH").delete()
    DBSession.query(State).filter_by(postal_code = "NJ").delete()
    DBSession.query(State).filter_by(postal_code = "NM").delete()
    DBSession.query(State).filter_by(postal_code = "NV").delete()
    DBSession.query(State).filter_by(postal_code = "NY").delete()
    DBSession.query(State).filter_by(postal_code = "OH").delete()
    DBSession.query(State).filter_by(postal_code = "OK").delete()
    DBSession.query(State).filter_by(postal_code = "OR").delete()
    DBSession.query(State).filter_by(postal_code = "PA").delete()
    DBSession.query(State).filter_by(postal_code = "RI").delete()
    DBSession.query(State).filter_by(postal_code = "SC").delete()
    DBSession.query(State).filter_by(postal_code = "SD").delete()
    DBSession.query(State).filter_by(postal_code = "TN").delete()
    DBSession.query(State).filter_by(postal_code = "TX").delete()
    DBSession.query(State).filter_by(postal_code = "UT").delete()
    DBSession.query(State).filter_by(postal_code = "VA").delete()
    DBSession.query(State).filter_by(postal_code = "VT").delete()
    DBSession.query(State).filter_by(postal_code = "WA").delete()
    DBSession.query(State).filter_by(postal_code = "WI").delete()
    DBSession.query(State).filter_by(postal_code = "WV").delete()
    DBSession.query(State).filter_by(postal_code = "WY").delete()
    
    
