#autogenerated by sqlautocode

import time

from sqlalchemy import *
from sqlalchemy.orm import mapper, relation
from sqlalchemy import Table, ForeignKey, Column
from sqlalchemy.types import Integer, Unicode
#from sqlalchemy.orm import relation, backref

from tg21_sample_data.model import DeclarativeBase, metadata, DBSession
import transaction

class DataMigration(DeclarativeBase):
    __tablename__ = 'data_migration'
    
    #column definitions
    date_created = Column(u'date_created', DateTime(timezone=False))
    id = Column(u'id', Integer(), primary_key=True, nullable=False)
    unique_code = Column(u'unique_code', Text(length=None, convert_unicode=False, assert_unicode=None), unique=True)
    
    #relation definitions
    
    
    # methods
    def __init__(self, unique_code):
        self.unique_code = unique_code
        self.date_created = time.localtime()
    

