#autogenerated by sqlautocode

from sqlalchemy import *
from sqlalchemy.orm import mapper, relation
from sqlalchemy import Table, ForeignKey, Column
from sqlalchemy.types import Integer, Unicode
#from sqlalchemy.orm import relation, backref

from tg21_sample_data.model import DeclarativeBase, metadata, DBSession

class State(DeclarativeBase):
    __tablename__ = 'state'
    
    #column definitions
    id = Column(u'id', Integer(), primary_key=True, nullable=False)
    name = Column(u'name', Text(length=None, convert_unicode=False, assert_unicode=None))
    postal_code = Column(u'postal_code', String(length=2, convert_unicode=False, assert_unicode=None))
    
    #relation definitions
    
    
    
    # methods
    def __init__(self, name, postal_code):
        self.name = name
        self.postal_code = postal_code
